[tools]
aws = { version = "2.32.26", symlink_bins = "true" }
bun = "1.3.5"
github-cli = "2.83.1"
neovim = "0.11.5"
node = "22.21.1"
starship = "1.24.1"
terraform = "1.14.3"
terraformer = "0.8.30"
tflint = "0.60.0"
tfsec = "1.28.14"
